[package]
authors = [
    "Jorge Aparicio <jorge@japaric.io>",
    "The Embedded Linux Team <embedded-linux@teams.rust-embedded.org>",
]
categories = ["embedded", "hardware-support"]
description = "Implementation of the `embedded-hal` traits for Linux devices"
keywords = ["Linux", "hal"]
license = "MIT OR Apache-2.0"
name = "linux-embedded-hal"
repository = "https://github.com/rust-embedded/linux-embedded-hal"
version = "0.3.2"
readme = "README.md"

[features]
gpio_sysfs = ["sysfs_gpio"]
gpio_cdev = ["gpio-cdev"]
i2c = ["i2cdev"]
spi = ["spidev"]

default = [ "gpio_cdev", "gpio_sysfs", "i2c", "spi" ]

[dependencies]
embedded-hal = { version = "0.2.6", features = ["unproven"] }
gpio-cdev = { version = "0.5", optional = true }
sysfs_gpio = { version = "0.6", optional = true }

i2cdev = { version = "0.5", optional = true }
nb = "0.1.3"
serial-core = "0.4.0"
serial-unix = "0.4.0"
spidev = { version = "0.5", optional = true }
void = "1"

[dev-dependencies]
openpty = "0.1.0"

[dependencies.cast]
# we don't need the `Error` implementation
default-features = false
version = "0.3"
